### ISSUE TITLE
feign.codec.EncodeException: null

### ISSUE THREAD

**Issue by KAKAROTS** [spring-cloud/spring-cloud-openfeign#1025]
myFeign:
```
    @PostMapping("/feature/values")
    FeatureRunResp getResult(@RequestBody FeatureRunReq req);
```

stackTrace:
```
feign.codec.EncodeException: null
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:401)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:232)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:84)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory$1.proceed(FeignCachingInvocationHandlerFactory.java:66)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:351)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
	at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory.lambda$create$1(FeignCachingInvocationHandlerFactory.java:53)
	at com.sun.proxy.$Proxy192.getResult(Unknown Source)
	at cn.caijiajia.magicquery.service.invoke.impl.MagicQueryFeatureInvokeServiceImpl.execute(MagicQueryFeatureInvokeServiceImpl.java:49)
	at cn.caijiajia.magicquery.service.FeatureExecutorService.lambda$null$3(FeatureExecutorService.java:66)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at cn.caijiajia.framework.stl.StlRunnable.run(StlRunnable.java:73)
	at cn.caijiajia.framework.tracing.async.TraceRunnable.run(TraceRunnable.java:72)
	at cn.caijiajia.tp.starter.wrapper.MetricRunnable.run(MetricRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:108)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:360)
	at com.alibaba.fastjson.serializer.ASMSerializer_32_FeatureRunReq.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	at com.alibaba.fastjson.JSON.writeJSONStringWithFastJsonConfig(JSON.java:1059)
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:314)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:246)
	at org.springframework.cloud.openfeign.support.SpringEncoder.checkAndWrite(SpringEncoder.java:217)
	at org.springframework.cloud.openfeign.support.SpringEncoder.encodeWithMessageConverter(SpringEncoder.java:146)
	at org.springframework.cloud.openfeign.support.SpringEncoder.encode(SpringEncoder.java:134)
	at org.springframework.cloud.openfeign.support.PageableSpringEncoder.encode(PageableSpringEncoder.java:101)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:396)
```

**Comment by OlgaMaciaszek** [comment]
Hello @KAKAROTS, thanks for reporting the issue. Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by KAKAROTS** [comment]
it looks like AsmSerializer problem

**Comment by KAKAROTS** [comment]
it looks like AsmSerializer problem

**Comment by OlgaMaciaszek** [comment]
We will not be able to verify the issue without a sample. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue if you would like us to look into it.
