### ISSUE TITLE
Feign 2.1.0 doesn't handle properly Iterable as method parameter

### ISSUE THREAD

**Issue by psemeniuk** [spring-cloud/spring-cloud-openfeign#135]
After upgrade to spring-cloud-openfeign:2.1.0.RELEASE we have problem in Feign clients with Vavr collections as input parameters. 
```
Caused by: java.lang.IllegalStateException: Could not resolve element type of Iterable type @org.springframework.web.bind.annotation.RequestParam io.vavr.collection.Set<java.lang.String>. Not declared?
	at feign.Util.checkState(Util.java:127)
	at org.springframework.cloud.openfeign.support.SpringMvcContract.createTypeDescriptor(SpringMvcContract.java:281)
	at org.springframework.cloud.openfeign.support.SpringMvcContract.processAnnotationsOnParameter(SpringMvcContract.java:258)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:110)
	at org.springframework.cloud.openfeign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:147)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:66)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:154)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:52)
	at feign.Feign$Builder.target(Feign.java:251)
	at org.springframework.cloud.openfeign.HystrixTargeter.target(HystrixTargeter.java:37)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:226)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:254)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:235)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
```

After analysis i think that problem is because of wrong assumption in `org.springframework.cloud.openfeign.support.SpringMvcContract#createTypeDescriptor.`
There is check whether parameter is implementation of Iterable. But method `org.springframework.core.convert.TypeDescriptor#getElementTypeDescriptor` itself operates on Collection - not Iterable (by the way idk why, i don't see any problem with that)

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Did this ever work?

**Comment by psemeniuk** [comment]
Yes, on Finchley.RC1 works OOTB. I think it's designed to work with Iterables (juding from mentioned method).

**Comment by spencergibb** [comment]
an RC isn't supported, did it work on RELEASE or SR2?

**Comment by psemeniuk** [comment]
On Finchley.RELEASE also seems to work. 
Reproduced on: https://github.com/psemeniuk/feign-error/blob/master/src/test/java/com/example/feignerror/FeignErrorApplicationTests.java

**Comment by spencergibb** [comment]
So this was the cause https://github.com/spring-cloud/spring-cloud-openfeign/pull/48
