### ISSUE TITLE
Feign Client FastJson OOM

### ISSUE THREAD

**Issue by nicqchen** [spring-cloud/spring-cloud-openfeign#212]

**Comment by nicqchen** [comment]
java.lang.OutOfMemoryError: Java heap space
	at com.fasterxml.jackson.core.util.BufferRecycler.balloc(BufferRecycler.java:155)
	at com.fasterxml.jackson.core.util.BufferRecycler.allocByteBuffer(BufferRecycler.java:96)
	at com.fasterxml.jackson.core.util.BufferRecycler.allocByteBuffer(BufferRecycler.java:86)
	at com.fasterxml.jackson.core.io.IOContext.allocWriteEncodingBuffer(IOContext.java:160)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.<init>(UTF8JsonGenerator.java:122)
	at com.fasterxml.jackson.core.JsonFactory._createUTF8Generator(JsonFactory.java:1426)
	at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1139)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:255)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.writeInternal(AbstractGenericHttpMessageConverter.java:112)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.cloud.openfeign.support.SpringEncoder.encode(SpringEncoder.java:112)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:372)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:224)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)

**Comment by ryanjbaxter** [comment]
There is no information in this issue that points to an issue with Spring Cloud OpenFeign
