### ISSUE TITLE
java.lang.IllegalStateException: Overrides unsupported: 

### ISSUE THREAD

**Issue by wulilele** [spring-cloud/spring-cloud-openfeign#344]
Caused by: java.lang.IllegalStateException: Overrides unsupported: 
	at feign.Util.checkState(Util.java:130) ~[feign-core-10.2.3.jar:na]
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:67) ~[feign-core-10.2.3.jar:na]
	at com.alibaba.cloud.sentinel.feign.SentinelContractHolder.parseAndValidatateMetadata(SentinelContractHolder.java:49) ~[spring-cloud-alibaba-sentinel-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:154) ~[feign-core-10.2.3.jar:na]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:52) ~[feign-core-10.2.3.jar:na]
	at feign.Feign$Builder.target(Feign.java:251) ~[feign-core-10.2.3.jar:na]
	at org.springframework.cloud.openfeign.HystrixTargeter.target(HystrixTargeter.java:36) ~[spring-cloud-openfeign-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:238) ~[spring-cloud-openfeign-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:267) ~[spring-cloud-openfeign-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:247) ~[spring-cloud-openfeign-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 43 common frames omitted

**Comment by spencergibb** [comment]
Unfortunately, a stack trace with no context isn't helpful. Can you specify boot and cloud versions, your configuration and your feign client?

**Comment by wulilele** [comment]
org.springframework.cloud:Greenwich.SR2
org.springframework.boot:2.1.6.RELEASE
