### ISSUE TITLE
"original request is required" with SPO 2.2.1 & Feign 10

### ISSUE THREAD

**Issue by drallieiv** [spring-cloud/spring-cloud-openfeign#364]
Using spring cloud openfeign 2.2.1 (Feign 10)

```
[INFO]       +- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.2.1.RELEASE:compile
[INFO]       |  +- io.github.openfeign:feign-core:jar:10.4.0:compile
[INFO]       |  +- io.github.openfeign:feign-slf4j:jar:10.4.0:compile
[INFO]       |  \- io.github.openfeign:feign-hystrix:jar:10.4.0:compile
[INFO]       \- io.github.openfeign:feign-httpclient:jar:10.4.0:compile
```

When calling a simple webservice that answers a HTTP 200 with a very basic body.
I am getting a stacktrace 

```
java.lang.IllegalStateException: original request is required
        at feign.Util.checkState(Util.java:130)
        at feign.Response.<init>(Response.java:49)
        at feign.Response.<init>(Response.java:40)
        at feign.Response$Builder.build(Response.java:136)
        at feign.httpclient.ApacheHttpClient.toFeignResponse(ApacheHttpClient.java:190)
        at feign.httpclient.ApacheHttpClient.execute(ApacheHttpClient.java:88)
        at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:114)
        at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:94)
```

It was not happening before upgrading to newer Spring Version

**Comment by spencergibb** [comment]
Can you provide a minimal sample that recreates the problem. It should be a GitHub project or zip file attached to this issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
