### ISSUE TITLE
Getting 400 reading while load increase for feign-client

### ISSUE THREAD

**Issue by pratikdandavate** [spring-cloud/spring-cloud-openfeign#424]
I'm using open-feign and I'm getting 400 error when the list size too large
If the list size is small then the execution succeeds

I'm using: `Hoxton.RELEASE` with Spring-boot version `2.2.1.RELEASE`

```
Caused by: feign.FeignException: status 400 reading Service#method(List,String); content:
    at feign.FeignException.errorStatus(FeignException.java:62)
    at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
    at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301)
    at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297)
    at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
    ... 26 common frames omitted
```

**Comment by spencergibb** [comment]
Hoxton.RELEASE has been superseded by 8 releases now. Can you retry with Hoxton.SR8 and a new version of spring boot?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
