### ISSUE TITLE
Issue with Feign Client GET request call with query PARAM having special characters are failing with below exception. IPV6 kubernates cluster

### ISSUE THREAD

**Issue by vasureddys** [spring-cloud/spring-cloud-openfeign#448]
Issue with Feign client GET request call with query PARAM having special characters are failing with below exception

Spring version : 2.3.4.RELEASE
Spring Cloud version : Hoxton.SR8
Java version : open jdk 11
Environment : Kubernates cluster environment with microservices.
Cluster setup is with IPV6. All the communiation between microservices via IPV6.

Test case scenario :
=====================
Request received from Frontend to one of the microservice say "Service A". Microservice Service A required information from Microservice Service B.
To get the data from Microservice Service B, we are makign a Feign Client call from Microservice Service A.
Request URL from Service A to Service B is:
http://serviceB/api/v1/checkEmailUnique?email=sampleemail@gmail.com

When we make a call, java trace as 
Step1 :
```
BlockingLoadBalancerClient.reconstructURI(BlockingLoadBalancerClient.java:75)
@Override
public URI reconstructURI(ServiceInstance serviceInstance, URI original) {
	return LoadBalancerUriTools.reconstructURI(serviceInstance, original);
}
```

Here `serviceInstance` has information about the IP address (IPV6 : 240b:c0e0:202:5e2b:b424:2:0:4b4), port (8001) and service name (serviceB). 
original : http://serviceB/api/v1/checkEmailUnique?email=sampleemail%40gmail.com

Step2 :
```
/**
 * Modifies the URI in order to redirect the request to a service instance of choice.
 * @param serviceInstance the {@link ServiceInstance} to redirect the request to.
 * @param original the {@link URI} from the original request
 * @return the modified {@link URI}
 */
public static URI reconstructURI(ServiceInstance serviceInstance, URI original) {
	if (serviceInstance == null) {
		throw new IllegalArgumentException("Service Instance cannot be null.");
	}
	return doReconstructURI(serviceInstance, original);
}
```

Step3 :
```
private static URI doReconstructURI(ServiceInstance serviceInstance, URI original) {
	String host = serviceInstance.getHost();
	String scheme = Optional.ofNullable(serviceInstance.getScheme())
			.orElse(computeScheme(original, serviceInstance));
	int port = computePort(serviceInstance.getPort(), scheme);

	if (Objects.equals(host, original.getHost()) && port == original.getPort()
			&& Objects.equals(scheme, original.getScheme())) {
		return original;
	}

	boolean encoded = containsEncodedParts(original);
	return UriComponentsBuilder.fromUri(original).scheme(scheme).host(host).port(port)
			.build(encoded).toUri();
}
```

In above code, encoded value is requred as true because url is encloded.
`boolean encoded = containsEncodedParts(original);`

Step 4 :
--------
```
public UriComponents build(boolean encoded) {
	return buildInternal(encoded ?
			EncodingHint.FULLY_ENCODED :
			this.encodeTemplate ? EncodingHint.ENCODE_TEMPLATE : EncodingHint.NONE);
}
```

Step 5: `EncodingHint.FULLY_ENCODED` send
---------------------------------------
```
private UriComponents buildInternal(EncodingHint hint) {
	UriComponents result;
	if (this.ssp != null) {
		result = new OpaqueUriComponents(this.scheme, this.ssp, this.fragment);
	}
	else {
		HierarchicalUriComponents uric = new HierarchicalUriComponents(this.scheme, this.fragment,
				this.userInfo, this.host, this.port, this.pathBuilder.build(), this.queryParams,
				hint == EncodingHint.FULLY_ENCODED);

		result = hint == EncodingHint.ENCODE_TEMPLATE ? uric.encodeTemplate(this.charset) : uric;
	}
	if (!this.uriVariables.isEmpty()) {
		result = result.expand(name -> this.uriVariables.getOrDefault(name, UriTemplateVariables.SKIP_VALUE));
	}
	return result;
}
```

Step 6: Because encoding value is true its calls a method `verify()...` below...
----------
```
HierarchicalUriComponents uric = new HierarchicalUriComponents(this.scheme, this.fragment,
				this.userInfo, this.host, this.port, this.pathBuilder.build(), this.queryParams,
				hint == EncodingHint.FULLY_ENCODED);
			

/**
 * Package-private constructor. All arguments are optional, and can be {@code null}.
 * @param scheme the scheme
 * @param userInfo the user info
 * @param host the host
 * @param port the port
 * @param path the path
 * @param query the query parameters
 * @param fragment the fragment
 * @param encoded whether the components are already encoded
 */
HierarchicalUriComponents(@Nullable String scheme, @Nullable String fragment, @Nullable String userInfo,
		@Nullable String host, @Nullable String port, @Nullable PathComponent path,
		@Nullable MultiValueMap<String, String> query, boolean encoded) {

	super(scheme, fragment);

	this.userInfo = userInfo;
	this.host = host;
	this.port = port;
	this.path = path != null ? path : NULL_PATH_COMPONENT;
	this.queryParams = query != null ? CollectionUtils.unmodifiableMultiValueMap(query) : EMPTY_QUERY_PARAMS;
	this.encodeState = encoded ? EncodeState.FULLY_ENCODED : EncodeState.RAW;

	// Check for illegal characters..
	if (encoded) {
		verify();
	}
}
```

Step 7: In verify method. `verifyUriComponent(this.host, getHostType());`
----------
```
/**
 * Check if any of the URI components contain any illegal characters.
 * @throws IllegalArgumentException if any component has illegal characters
 */
private void verify() {
	verifyUriComponent(getScheme(), Type.SCHEME);
	verifyUriComponent(this.userInfo, Type.USER_INFO);
	verifyUriComponent(this.host, getHostType());
	this.path.verify();
	this.queryParams.forEach((key, values) -> {
		verifyUriComponent(key, Type.QUERY_PARAM);
		for (String value : values) {
			verifyUriComponent(value, Type.QUERY_PARAM);
		}
	});
	verifyUriComponent(getFragment(), Type.FRAGMENT);
}
```

Step 8: Here host IP is : 240b:c0e0:202:5e2b:b424:2:0:4b4 and this doesn't have "[" hence its treated as IPV4 address.
======================================================================================================================
```
private Type getHostType() {
	return (this.host != null && this.host.startsWith("[") ? Type.HOST_IPV6 : Type.HOST_IPV4);
}
```

Step 9: `verifyUriComponent` method throws below exception....
=================
```
verifyUriComponent(this.host, getHostType());

private static void verifyUriComponent(@Nullable String source, Type type) {
	if (source == null) {
		return;
	}
	int length = source.length();
	for (int i = 0; i < length; i++) {
		char ch = source.charAt(i);
		if (ch == '%') {
			if ((i + 2) < length) {
				char hex1 = source.charAt(i + 1);
				char hex2 = source.charAt(i + 2);
				int u = Character.digit(hex1, 16);
				int l = Character.digit(hex2, 16);
				if (u == -1 || l == -1) {
					throw new IllegalArgumentException("Invalid encoded sequence \"" +
							source.substring(i) + "\"");
				}
				i += 2;
			}
			else {
				throw new IllegalArgumentException("Invalid encoded sequence \"" +
						source.substring(i) + "\"");
			}
		}
		else if (!type.isAllowed(ch)) {
			throw new IllegalArgumentException("Invalid character '" + ch + "' for " +
					type.name() + " in \"" + source + "\"");
		}
	}
}
```	

Exception stack trace:
=========================
```
2020-12-18 08:50:53.488 DEBUG [,bf7c6d79a8c83a34,bf543439eefefbf5,true] 10 --- [r-management-24] c.f.TraceFeignBlockingLoadBalancerClient : Before send
2020-12-18 08:50:53.489 DEBUG [,bf7c6d79a8c83a34,bf543439eefefbf5,true] 10 --- [r-management-24] c.f.TraceFeignBlockingLoadBalancerClient : Exception thrown

java.lang.IllegalArgumentException: Invalid character ':' for HOST_IPV4 in "240b:c0e0:202:5e2b:b424:2:0:4b4"
        at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:416)
        at org.springframework.web.util.HierarchicalUriComponents.verify(HierarchicalUriComponents.java:379)
        at org.springframework.web.util.HierarchicalUriComponents.<init>(HierarchicalUriComponents.java:145)
        at org.springframework.web.util.UriComponentsBuilder.buildInternal(UriComponentsBuilder.java:417)
        at org.springframework.web.util.UriComponentsBuilder.build(UriComponentsBuilder.java:406)
        at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.doReconstructURI(LoadBalancerUriTools.java:111)
        at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.reconstructURI(LoadBalancerUriTools.java:95)
        at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.reconstructURI(BlockingLoadBalancerClient.java:75)
        at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:73)
        at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignBlockingLoadBalancerClient.execute(TraceFeignBlockingLoadBalancerClient.java:76)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
        at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:109)
        at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
        at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:71)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

2020-12-18 08:50:53.490 DEBUG [,bf7c6d79a8c83a34,bf7c6d79a8c83a34,true] 10 --- [nio-8003-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Using @ExceptionHandler com.mavenir.dep.accountmanagement.exception.CustomResponseEntityExceptionHandler#handleHystrixRuntimeException(HystrixRuntimeException, WebRequest)
2020-12-18 08:50:53.491 ERROR [,bf7c6d79a8c83a34,bf7c6d79a8c83a34,true] 10 --- [nio-8003-exec-2] a.e.CustomResponseEntityExceptionHandler : Hystrix Runtime Exception caused by :
```

**Comment by OlgaMaciaszek** [comment]
Hello, @vasureddys can you tell me which `ServiceInstanceListSupplier` and `DiscoveryClient` is being used and paste a `String` representation of the returned service instance (object field values)? (You can see returned service instances, for example, by debugging at this method: https://github.com/spring-cloud/spring-cloud-commons/blob/eb32ea8f21103f59778c27cee48b3930dd2728af/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java#L86)

**Comment by vasureddys** [comment]
We are using spring-cloud-loadbalancer-2.2.5.RELEASE version.

**Comment by OlgaMaciaszek** [comment]
I understand. Will you be able to provide the information requested above?

**Comment by vasureddys** [comment]
I will need to setup the cluster and then need to debug from eclipse to provide the requested information. Will do it and provide it.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by coolbeevip** [comment]
same issue

**Comment by OlgaMaciaszek** [comment]
The root issue is in SC commons. Closing in favour of  https://github.com/spring-cloud/spring-cloud-commons/issues/558.

**Comment by santoshkumarcts** [comment]
@OlgaMaciaszek  Apology for commenting on closed ticket, Could you please point me `The root issue is in SC commons`. and the fix.
we are also facing the same issue.
Thank you

**Comment by santoshkumarcts** [comment]
Hi @OlgaMaciaszek apologize for commenting on the closed ticket.
I am currently working on Spring Client Side Load Balancer with Spring Cloud Kubernetes using IPV6.
Facing the issue mentioned here.

Please find the below analysis.

The `HierarchicalUriComponents` class encounters an issue when validating an IPv6 URL with query parameters. The problem stems from the `getHostType` method incorrectly classifying the host type as IPV4 due to the lack of square brackets around the IPv6 host during the method call. Which resulted in call failure with the below exception.

> Invalid character ':' for HOST_IPV4 in \"fd00::1:e4f7:eb43:bb46:a1ff\"

1. Below is the ipv6 URL with encoded query params

> {"instant":{"epochSecond":1704870798,"nanoOfSecond":480180210},"thread":"boundedElastic-2","level":"DEBUG","loggerName":"org.springframework.cloud.client.loadbalancer.reactive.ExchangeFilterFunctionUtils","message":"create URI with request org.springframework.web.reactive.funct    ion.client.DefaultClientRequestBuilder$BodyInserterRequest@14ba07ed: http%3A%2F%2Ftest-occnp-test-ds%3A8000%2Ftest%2Fv0%2Ftest-data%3FreqParam%3D%7B%E2%80%9Dparent-a1%22%3A%7B%E2%80%9Cattrib1%E2%80%9D%3Atrue%2C%E2%80%9Cattrib2%22%3A%E2%80%9Cvalue1%E2%80%9D%2C%E2%80%9Cattrib3%22%3A3%2C%E2%80%9Cparent-a2%E2%80%9D%3A%7B%E2%80%9Cattrib4%22%3A17%2C%E2%80%9Cattrib5%E2%80%9D%3A%E2%80%9Cabc117%22%7D%7D%7D%26param%3D%7B%E2%80%9Cparent-b1%E2%80%9D%3A%7B%E2%80%9Cattrib11%22%3Atrue%2C%E2%80%9Cattrib12%E2%80%9D%3A%E2%80%9Cvalue1%22%2C%E2%80%9Cattrib13%E2%80%9D%3A3%2C%E2%80%9Cparent-b2%22%3A%7B%E2%80%9Cattrib14%E2%80%9D%3A17%2C%E2%80%9Cattrib15%22%3A%E2%80%9Cabc117%E2%80%9D%7D%7D%7D","endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.LogAdapter$Log4jLog","thr    eadId":70,"threadPriority":5,"messageTimestamp":"2024-01-10T07:13:18.480+0000"}


2. Here is the service instance information retrieved from Kubernetes service discovery.

`DefaultKubernetesServiceInstance[instanceId=xxxxxx-xxxx-4186-8350-43448d9a41a5, serviceId=test-ds, host=fd01::1:e4f7:eb43:bb46:a1ff, port=8000, metadata={k8s_namespace=test, primary-port-name=http2-text, app.kubernetes.io/name=test, microservice=test, meta.helm.sh/release-name=test, meta.helm.sh/release-namespace=test, cluster-autoscaler.kubernetes.io/safe-to-evict=false, port.https=8443, port.http2-text=8000, io.kompose.service=test, type=ClusterIP, app.kubernetes.io/instance=test, helm.sh/chart=test-23.4.0, app.kubernetes.io/managed-by=Helm, engVersion=23.4.0, application=test, vendor=Oracle, app.kubernetes.io/part-of=test, category=common, mktgVersion=1.0.0, kubectl.kubernetes.io/last-applied-configuration={\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"cluster-autoscaler.kubernetes.io/safe-to-evict\":\"false\",\"meta.helm.sh/release-name\":\"test\",\"meta.helm.sh/release-namespace\":\"test\"},\"creationTimestamp\":\"2024-01-04T21:51:13Z\",\"labels\":{\"app.kubernetes.io/instance\":\"test\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"test\",\"app.kubernetes.io/part-of\":\"test\",\"app.kubernetes.io/version\":\"1.0.0\",\"application\":\"test\",\"category\":\"common\",\"engVersion\":\"23.4.0\",\"helm.sh/chart\":\"test-23.4.0\",\"io.kompose.service\":\"test-ocpm-test\",\"microservice\":\"test\",\"mktgVersion\":\"1.0.0\",\"primary-port-name\":\"http2-text\",\"vendor\":\"Oracle\"},\"name\":\"test-test-test-ds\",\"namespace\":\"test\",\"resourceVersion\":\"249835089\",\"uid\":\"xxxxxxxxxxxxxxxxd\"},\"spec\":{\"internalTraffictest\":\"Cluster\",\"ipFamilies\":[\"IPv6\"],\"ipFamilytest\":\"RequireDualStack\",\"ports\":[{\"name\":\"http2-text\",\"port\":8000,\"protocol\":\"TCP\",\"targetPort\":8000},{\"name\":\"https\",\"port\":1234,\"protocol\":\"TCP\",\"targetPort\":1234}],\"selector\":{\"io.kompose.service\":\"test-ocpm-test\"},\"sessionAffinity\":\"None\",\"type\":\"ClusterIP\"},\"status\":{\"loadBalancer\":{}}}\n, app.kubernetes.io/version=1.0.0}, secure=false, namespace=test, cluster=null, podMetadata={}]`

Please let me know if you need any further information.

Thank you.

**Comment by OlgaMaciaszek** [comment]
Hello @santoshkumarcts , 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by santoshkumarcts** [comment]
Thank you for your response, @OlgaMaciaszek . Below are two sample repositories where the issue can be replicated. 
Follow these steps to configure the projects:
1. Download and execute the **loadbalancer-server**. (https://github.com/santoshkumarcts/loadbalancer-server)
2. Run multiple instances with unique names and ports using specified program arguments, e.g.,
 `--server.instance.id=2 --server.port=8081`.
4. Download the **loadbalancer-client**. ( https://github.com/santoshkumarcts/loadbalancer-client ) 

You can reproduce the issue by running the **loadbalancer-client**.

**Comment by santoshkumarcts** [comment]
[loadbalancer-client-error.log](https://github.com/spring-cloud/spring-cloud-openfeign/files/13915450/loadbalancer-client-error.log)

Please find the attached error log file.

**Comment by santoshkumarcts** [comment]
Hi @OlgaMaciaszek Have you had a chance to review the mentioned issue?

**Comment by santoshkumarcts** [comment]
@OlgaMaciaszek  Waiting for your feedback.

**Comment by OlgaMaciaszek** [comment]
Hello @santoshkumarcts, we will get to it, but we have a large queue of issues, so it'll take some time.
