### ISSUE TITLE
Health check & SimpleDiscoveryClient : urls interpreted as service name

### ISSUE THREAD

**Issue by MarneusCalgarXP** [spring-cloud/spring-cloud-openfeign#567]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

* spring-cloud-starter-openfeign / spring-cloud-starter-loadbalancer 3.0.3
* spring-boot-starter-web / spring-boot-starter-actuator 2.5.2

I'm trying to add health check on a SimpleDiscoveryClient (blocking mode).
Everything works until I activate the health check (blocking mode)
when I activate the health check, I got errors like:

```
2021-06-30 11:40:01.410  WARN 5471 --- [oundedElastic-1] c.l.c.ServiceInstanceListSupplierBuilder : LoadBalancerCacheManager not available, returning delegate without caching.
2021-06-30 11:40:01.414  WARN 5471 --- [oundedElastic-2] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 127.0.0.1
2021-06-30 11:40:01.420  WARN 5471 --- [oundedElastic-2] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 127.0.0.1
2021-06-30 11:40:01.423  WARN 5471 --- [oundedElastic-1] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: hello
```

**Sample**

Here's my test case
(a web  controller using feign client to call feign controller)

* FeignConfiguration.java

```java
@EnableFeignClients("my.package")
@EnableDiscoveryClient
@LoadBalancerClient(value = "hello", configuration = CustomLoadBalancerConfiguration.class)
public class FeignConfiguration {

    @LoadBalanced
    @Bean
    public RestTemplate restTemplate() {
        final RestTemplate restTemplate = new RestTemplate();
        return restTemplate;
    }

}
```
* CustomLoadBalancerConfiguration.java :
```
@Slf4j
public class CustomLoadBalancerConfiguration {

    @Bean
    public ServiceInstanceListSupplier serviceInstanceListSupplier(
            ConfigurableApplicationContext context) {
        return ServiceInstanceListSupplier.builder()
                .withHints()
                .withBlockingDiscoveryClient()
                .withBlockingHealthChecks() // <-- when present, bug occurs
                .build(context);
    }

}
```

* HelloFeignInterface
```java
public interface HelloFeignInterface {

    /**
     * renvoie "hello"
     **/
    @GetMapping(path = "/feign/hello")
    String hello();
}```

* HelloFeignController
```java
@RestController
public class HelloFeignController implements HelloFeignInterface {

    @Override
    public String hello() {
        return "hello";
    }
}
```

* HelloFeignClient.java
```java
@FeignClient("hello")
public interface HelloFeignClient extends HelloFeignInterface {

}
```

TestController
```
@RestController
@RequestMapping("/")
public class TestController {

    @Autowired
    private HelloFeignClient helloFeignClient;

    /** says "hello" (through feign call) */
    @GetMapping("/hello")
    public String hello() {
        return helloFeignClient.hello();
    }
}
```
application.properties

```
spring.cloud.loadbalancer.cache.enabled=false
spring.cloud.loadbalancer.health-check.interval=1s
spring.cloud.loadbalancer.health-check.refetch-instances=true
spring.cloud.loadbalancer.health-check.refetch-instances-interval=1s
spring.cloud.discovery.client.simple.instances.hello[0].uri=http://127.0.0.1:8081
spring.cloud.discovery.client.simple.instances.hello[1].uri=http://127.0.0.1:8080
```

when calling testcontroller:
```
curl -XGET http://localhost:8080/hello
{"timestamp":"2021-06-30T09:51:08.158+00:00","status":500,"error":"Internal Server Error","path":"/hello"}%
```

in app logs
```
2021-06-30 11:51:08.122  WARN 6057 --- [oundedElastic-2] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 127.0.0.1
2021-06-30 11:51:08.123  WARN 6057 --- [oundedElastic-1] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: hello
2021-06-30 11:51:08.123  WARN 6057 --- [nio-8080-exec-1] .s.c.o.l.FeignBlockingLoadBalancerClient : Load balancer does not contain an instance for the service hello
2021-06-30 11:51:08.144 ERROR 6057 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://hello/feign/hello] [HelloFeignClient#hello()]: [Load balancer does not contain an instance for the service hello]] with root cause

feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://hello/feign/hello] [HelloFeignClient#hello()]: [Load balancer does not contain an instance for the service hello]
	at feign.FeignException.serverErrorStatus(FeignException.java:237) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:180) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[feign-core-10.12.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.12.jar:na]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.12.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.12.jar:na]
	at com.sun.proxy.$Proxy75.hello(Unknown Source) ~[na:na]
	at fr.parcours5.p5feigntest.controller.TestController.hello(TestController.java:31) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.8.jar:5.3.8]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.48.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.8.jar:5.3.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.48.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.8.jar:5.3.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar:5.3.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.8.jar:5.3.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar:5.3.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.8.jar:5.3.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar:5.3.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.48.jar:9.0.48]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-06-30 11:51:09.129  WARN 6057 --- [oundedElastic-1] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 127.0.0.1
2021-06-30 11:51:09.134  WARN 6057 --- [oundedElastic-1] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 127.0.0.1
2021-06-30 11:51:09.141  WARN 6057 --- [oundedElastic-2] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: 127.0.0.1
```

Note : when health check is disabled, everything works fine

**Comment by MarneusCalgarXP** [comment]
With further tests, the problem seems to come from the `@LoadBalanced` annotation on the `RestTemplate` bean.
When removing the `@LoadBalanced` annotation, it works with health check.

EDIT : better way:
* let the `@LoadBalanced` annotation on the `RestTemplate` bean.
* provide a new `RestTemplate` for the health check:

```java
@Bean
    public ServiceInstanceListSupplier serviceInstanceListSupplier(
            ConfigurableApplicationContext context) {
        return ServiceInstanceListSupplier.builder()
                .withHints()
                .withBlockingDiscoveryClient()
                .withBlockingHealthChecks(new RestTemplate())
                .build(context);
    }
```

**Comment by MarneusCalgarXP** [comment]
(maybe just need some documentation about it ?)

**Comment by OlgaMaciaszek** [comment]
Moving to SC Commons as the issue seems related to the SC LoadBalancer only.
