### ISSUE TITLE
Failed to convert ResponseEntity object

### ISSUE THREAD

**Issue by eduardosilvaneto** [spring-cloud/spring-cloud-openfeign#673]
Hello, when invoking a remote method that returns a "responseEntity" object, the following error occurs:
``` 
java.io.IOException: Incomplete output stream
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1559)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at feign.Client$Default.convertResponse(Client.java:108)
	at feign.Client$Default.execute(Client.java:104)
	at org.springframework.cloud.openfeign.loadbalancer.LoadBalancerUtils.executeWithLoadBalancerLifecycleProcessing(LoadBalancerUtils.java:56)
	at org.springframework.cloud.openfeign.loadbalancer.RetryableFeignBlockingLoadBalancerClient.lambda$execute$2(RetryableFeignBlockingLoadBalancerClient.java:156)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225)
	at org.springframework.cloud.openfeign.loadbalancer.RetryableFeignBlockingLoadBalancerClient.execute(RetryableFeignBlockingLoadBalancerClient.java:103)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
```
The spring cloud feign version used is 2020.0.5

**Comment by OlgaMaciaszek** [comment]
Hello, @eduardosilvaneto, thanks for submitting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
It does not seem that the issue is in SC OpenFeign - there's problem processing the input stream with Java methods, the response might be corrupt. In any case, I can take a closer look at this for you, anyway, but in order to get this done, please, upgrade to `2021.0.0` (`2020.0.x` is no longer supported) and provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by eduardosilvaneto** [comment]
Thank you very much for your feedback. I really had something corrupting the file, maybe my VPN. Performing the test with the same code worked.

**Comment by eduardosilvaneto** [comment]
Thank you very much for your feedback. I really had something corrupting the file, maybe my VPN. Performing the test with the same code worked.

**Comment by eduardosilvaneto** [comment]
Thank you very much for your feedback. I really had something corrupting the file, maybe my VPN. Performing the test with the same code worked.
