### ISSUE TITLE
when use jdk17，the OnPropertyCondition of @FeignClient is class not found.

### ISSUE THREAD

**Issue by poolsnowhui** [spring-cloud/spring-cloud-openfeign#801]
**Describe the bug**
jdk17.0.2
java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.condition.OnPropertyCondition
    at java.base/java.lang.Class.forNameImpl(Native Method) ~[na:na]
    at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring-core-5.3.24.jar!/:5.3.24]
    at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324) ~[spring-core-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:225) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.24.jar!/:5.3.24]
    at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:155) ~[spring-cloud-context-3.1.5.jar!/:3.1.5]
    at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:108) ~[spring-cloud-context-3.1.5.jar!/:3.1.5]
    at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:203) ~[spring-cloud-context-3.1.5.jar!/:3.1.5]
    at org.springframework.cloud.openfeign.loadbalancer.RetryableFeignBlockingLoadBalancerClient.lambda$execute$2(RetryableFeignBlockingLoadBalancerClient.java:119) ~[spring-cloud-openfeign-core-3.1.5.jar!/:3.1.5]
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.4.jar!/:na]
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225) ~[spring-retry-1.3.4.jar!/:na]
    at org.springframework.cloud.openfeign.loadbalancer.RetryableFeignBlockingLoadBalancerClient.execute(RetryableFeignBlockingLoadBalancerClient.java:114) ~[spring-cloud-openfeign-core-3.1.5.jar!/:3.1.5]
    at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceRetryableFeignBlockingLoadBalancerClient.execute(TraceRetryableFeignBlockingLoadBalancerClient.java:79) ~[spring-cloud-sleuth-instrumentation-3.1.5.jar!/:3.1.5]
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:121) ~[feign-core-11.10.jar!/:na]
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:91) ~[feign-core-11.10.jar!/:na]
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-11.10.jar!/:na]

**Sample**
Get the interface of @FeignClient

Hopes you can help solve the problem!

**Comment by OlgaMaciaszek** [comment]
Closing in favour of gh-475.
