### ISSUE TITLE
AOT failed with 'className cannot be null'

### ISSUE THREAD

**Issue by benfromchina** [spring-cloud/spring-cloud-openfeign#845]
**AOT failed with 'className cannot be null'**
- Spring Cloud version: 2022.0.0

**Exception**
```java
Exception in thread "main" java.lang.IllegalArgumentException: className cannot be null
	at org.springframework.util.Assert.notNull(Assert.java:204)
	at org.springframework.cloud.openfeign.aot.FeignClientBeanFactoryInitializationAotProcessor$AotContribution.lambda$applyTo$1(FeignClientBeanFactoryInitializationAotProcessor.java:117)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.springframework.cloud.openfeign.aot.FeignClientBeanFactoryInitializationAotProcessor$AotContribution.applyTo(FeignClientBeanFactoryInitializationAotProcessor.java:124)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
```

**Code Position**
```java
@Override
public void applyTo(GenerationContext generationContext,
		BeanFactoryInitializationCode beanFactoryInitializationCode) {
	ProxyHints proxyHints = generationContext.getRuntimeHints().proxies();
	Set<String> feignClientRegistrationMethods = feignClientBeanDefinitions.values().stream()
			.map(beanDefinition -> {
				Assert.notNull(beanDefinition, "beanDefinition cannot be null");
				Assert.isInstanceOf(GenericBeanDefinition.class, beanDefinition);
				GenericBeanDefinition registeredBeanDefinition = (GenericBeanDefinition) beanDefinition;
				MutablePropertyValues feignClientProperties = registeredBeanDefinition.getPropertyValues();
				String className = (String) feignClientProperties.get("type");
				Assert.notNull(className, "className cannot be null");
```

**My pom.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.stark.springcloud</groupId>
		<artifactId>spring-cloud-alibaba</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>springcloud-auth-server</artifactId>

	<properties>
		<spring-boot.build-image.imageName>192.168.41.24/spring-cloud-alibaba/${project.artifactId}:${project.version}</spring-boot.build-image.imageName>
	</properties>

	<dependencies>
		<!-- spring-authorization-server start -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-authorization-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<!-- spring-authorization-server end -->
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis-reactive</artifactId>
		</dependency>
		<!-- openfeign start -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-loadbalancer</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>
		<!-- openfeign end -->
		<!-- sentinel start -->
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
		</dependency>
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-datasource-nacos</artifactId>
		</dependency>
		<!-- sentinel end -->
		<dependency>
			<groupId>com.stark.springcloud</groupId>
			<artifactId>springcloud-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
    </dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

**My application.yml**
```yml
spring:
  application:
    name: springcloud-auth-server
  profiles:
    active: dev
  cloud:
    refresh:
      enabled: false
    openfeign:
      client:
        refresh-enabled: false
      lazy-attributes-resolution: false
```

**Maven command**
```bash
mvn clean -Pnative spring-boot:build-image
```

**Comment by OlgaMaciaszek** [comment]
Hello @benfromchina, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, as a link to a repo with a small executable app instead of separate code fragments.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
