### ISSUE TITLE
Expected authority at index 7: http://

### ISSUE THREAD

**Issue by arnold-krutolevich** [spring-cloud/spring-cloud-openfeign#9]
Unable to construct URI from @FeignClient annotation.

`@FeignClient("avantgarde-security")`
`interface AuthenticationClient {`
` @PostMapping`
` fun authenticate(@RequestBody request: AuthenticationRequest): Token`
`}`

> java.lang.IllegalArgumentException: Expected authority at index 7: http://
	at java.net.URI.create(URI.java:852) ~[na:1.8.0_152]
	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.cleanUrl(LoadBalancerFeignClient.java:100) ~[spring-cloud-openfeign-core-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:58) ~[spring-cloud-openfeign-core-2.0.0.M1.jar:2.0.0.M1]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97) ~[feign-core-9.5.1.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.1.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.1.jar:na]

org.springframework.cloud:spring-cloud-starter-openfeign:2.0.0.M1

**Comment by ryanjbaxter** [comment]
What does your ribbon configuration look like?

**Comment by arnold-krutolevich** [comment]
No custom configuration for ribbon. Specified eureka discovery server in properties only.

**Comment by ryanjbaxter** [comment]
Can you provide the result of hitting http://<eureakserver>/eureka/apps?

**Comment by arnold-krutolevich** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<applications>
   <versions__delta>1</versions__delta>
   <apps__hashcode>UP_3_</apps__hashcode>
   <application>
      <name>AVANTGARDE-CRM</name>
      <instance>
         <instanceId>192.168.88.12:avantgarde-crm:8100</instanceId>
         <hostName>192.168.88.12</hostName>
         <app>AVANTGARDE-CRM</app>
         <ipAddr>192.168.88.12</ipAddr>
         <status>UP</status>
         <overriddenstatus>UNKNOWN</overriddenstatus>
         <port enabled="true">8100</port>
         <securePort enabled="false">443</securePort>
         <countryId>1</countryId>
         <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
            <name>MyOwn</name>
         </dataCenterInfo>
         <leaseInfo>
            <renewalIntervalInSecs>30</renewalIntervalInSecs>
            <durationInSecs>90</durationInSecs>
            <registrationTimestamp>1520861085566</registrationTimestamp>
            <lastRenewalTimestamp>1520861264832</lastRenewalTimestamp>
            <evictionTimestamp>0</evictionTimestamp>
            <serviceUpTimestamp>1520861084492</serviceUpTimestamp>
         </leaseInfo>
         <metadata>
            <management.port>8100</management.port>
            <jmx.port>62970</jmx.port>
         </metadata>
         <homePageUrl>http://192.168.88.12:8100/</homePageUrl>
         <statusPageUrl>http://192.168.88.12:8100/info</statusPageUrl>
         <healthCheckUrl>http://192.168.88.12:8100/health</healthCheckUrl>
         <vipAddress>avantgarde-crm</vipAddress>
         <secureVipAddress>avantgarde-crm</secureVipAddress>
         <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
         <lastUpdatedTimestamp>1520861085571</lastUpdatedTimestamp>
         <lastDirtyTimestamp>1520861084336</lastDirtyTimestamp>
         <actionType>ADDED</actionType>
      </instance>
   </application>
   <application>
      <name>AVANTGARDE-PROXY</name>
      <instance>
         <instanceId>192.168.88.12:avantgarde-proxy</instanceId>
         <hostName>192.168.88.12</hostName>
         <app>AVANTGARDE-PROXY</app>
         <ipAddr>192.168.88.12</ipAddr>
         <status>UP</status>
         <overriddenstatus>UNKNOWN</overriddenstatus>
         <port enabled="true">8080</port>
         <securePort enabled="false">443</securePort>
         <countryId>1</countryId>
         <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
            <name>MyOwn</name>
         </dataCenterInfo>
         <leaseInfo>
            <renewalIntervalInSecs>30</renewalIntervalInSecs>
            <durationInSecs>90</durationInSecs>
            <registrationTimestamp>1520861090570</registrationTimestamp>
            <lastRenewalTimestamp>1520861240487</lastRenewalTimestamp>
            <evictionTimestamp>0</evictionTimestamp>
            <serviceUpTimestamp>1520861090062</serviceUpTimestamp>
         </leaseInfo>
         <metadata>
            <management.port>8080</management.port>
            <jmx.port>63000</jmx.port>
         </metadata>
         <homePageUrl>http://192.168.88.12:8080/</homePageUrl>
         <statusPageUrl>http://192.168.88.12:8080/info</statusPageUrl>
         <healthCheckUrl>http://192.168.88.12:8080/health</healthCheckUrl>
         <vipAddress>avantgarde-proxy</vipAddress>
         <secureVipAddress>avantgarde-proxy</secureVipAddress>
         <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
         <lastUpdatedTimestamp>1520861090570</lastUpdatedTimestamp>
         <lastDirtyTimestamp>1520861089976</lastDirtyTimestamp>
         <actionType>ADDED</actionType>
      </instance>
   </application>
   <application>
      <name>AVANTGARDE-SECURITY</name>
      <instance>
         <instanceId>192.168.88.12:avantgarde-security:8200</instanceId>
         <hostName>192.168.88.12</hostName>
         <app>AVANTGARDE-SECURITY</app>
         <ipAddr>192.168.88.12</ipAddr>
         <status>UP</status>
         <overriddenstatus>UNKNOWN</overriddenstatus>
         <port enabled="true">8200</port>
         <securePort enabled="false">443</securePort>
         <countryId>1</countryId>
         <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
            <name>MyOwn</name>
         </dataCenterInfo>
         <leaseInfo>
            <renewalIntervalInSecs>30</renewalIntervalInSecs>
            <durationInSecs>90</durationInSecs>
            <registrationTimestamp>1520861096784</registrationTimestamp>
            <lastRenewalTimestamp>1520861246702</lastRenewalTimestamp>
            <evictionTimestamp>0</evictionTimestamp>
            <serviceUpTimestamp>1520861096271</serviceUpTimestamp>
         </leaseInfo>
         <metadata>
            <management.port>8200</management.port>
            <jmx.port>63022</jmx.port>
         </metadata>
         <homePageUrl>http://192.168.88.12:8200/</homePageUrl>
         <statusPageUrl>http://192.168.88.12:8200/info</statusPageUrl>
         <healthCheckUrl>http://192.168.88.12:8200/health</healthCheckUrl>
         <vipAddress>avantgarde-security</vipAddress>
         <secureVipAddress>avantgarde-security</secureVipAddress>
         <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
         <lastUpdatedTimestamp>1520861096784</lastUpdatedTimestamp>
         <lastDirtyTimestamp>1520861096189</lastDirtyTimestamp>
         <actionType>ADDED</actionType>
      </instance>
   </application>
</applications>
```

**Comment by ryanjbaxter** [comment]
Nothing there looks off to me.  Can you provide a sample that reproduces the problem?

**Comment by dzifuta** [comment]
This is just a confusing error message. You forgot to provide a value in your POST declaration here:
@PostMapping --> @PostMapping(value = "/bla")

**Comment by ryanjbaxter** [comment]
Closing based on @dzifuta's comment.  If you are still having an issue please reopen.
