### ISSUE TITLE
DTO with @lombok.Value + FeignClient + Native/AOT = Deserialization exception

### ISSUE THREAD

**Issue by dpozinen** [spring-cloud/spring-cloud-openfeign#966]
## Problem:

With the below setup:
```
@FeignClient(name = "play-client", configuration = PlayClientConfiguration.class)
public interface PlayClient {

    @GetMapping("/play-value")
    PlayResponseValue playValue(@RequestParam String item);

    @lombok.Value
    class PlayResponseValue {
        String result;
    }
}
```

I'm getting the following exception:
```
Caused by: org.springframework.web.client.RestClientException: Error while extracting response for type [class com.playtika.services.samples.PlayClient$PlayResponseValue] and content type [application/json]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:118)
        at org.springframework.cloud.openfeign.support.SpringDecoder.decode(SpringDecoder.java:75)
        at org.springframework.cloud.openfeign.support.ResponseEntityDecoder.decode(ResponseEntityDecoder.java:61)
        at feign.optionals.OptionalDecoder.decode(OptionalDecoder.java:36)
        at feign.InvocationContext.proceed(InvocationContext.java:36)
        ... 37 common frames omitted
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `com.playtika.services.samples.PlayClient$PlayResponseValue` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354)
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103)
        ... 41 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.playtika.services.samples.PlayClient$PlayResponseValue` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1739)
```

But everything works perfectly when using a java application (non native).

## Investigation results:

At first I thought this was a hint issue, but I checked and they were indeed automatically generated.
```
{
    "name": "com.playtika.services.samples.PlayClient$PlayResponseValue",
    "allDeclaredConstructors": true,
    "allDeclaredFields": true,
    "methods": [ { "name": "getResult", "parameterTypes": [ ] } ]
  }
```

I tried adding the constructor as a method hint manually, but that didn't help.

I also attempted to solve this by adding:
`lombok.anyConstructor.addConstructorProperties=true`, which ensured that this was my class file:
```
public static final class PlayResponseValue {
        private final String result;

        @ConstructorProperties({"result"})
        @Generated
        public PlayResponseValue(final String result) {
            this.result = result;
        }

        @Generated
        public String getResult() {
            return this.result;
        }
...
}
```
but that didn't help.

## Workarounds:

Everything works in either case:
* if the DTO is reimplemented to be a java `record`.
* when `@lombok.RequiredArgsConstructor(onConstructor_={@JsonCreator})` is added to the dto

These workarounds are generally acceptable, although would require a lot of effort to implement across multiple services.

Since the constructor is present, the hint for it as well, I believe that native should be able to detect everything just as java would.

### Environment
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.9+11.1 (build 17.0.9+11-LTS-jvmci-23.0-b21, mixed mode, sharing)
Spring Boot 3.1.6  
OpenFeign 4.0.4

(duplicate of https://github.com/spring-projects/spring-boot/issues/39197)

**Comment by OlgaMaciaszek** [comment]
Hello @dpozinen, thanks for reporting the issue. We do not offer dedicated support for Lombok, so the users would need to figure out the proper setup for themselves; if you do figure it out and would like to submit a PR, we would review it, but we are not planning to work on it ourselves.

**Comment by dpozinen** [comment]
hi @OlgaMaciaszek I have verified that this is not a Lombok issue. If I reimplement the class to what Lombok produces, except without the `@Generated` markers, specifically
```
    public static class PlayResponseValue {
        private final String result;

        @ConstructorProperties("result")
        public PlayResponseValue(String result) {
            this.result = result;
        }

        public String getResult() {
            return this.result;
        }
    }
```
The issue still persists.

Please have a look

**Comment by OlgaMaciaszek** [comment]
@dpozinen I was not able to reproduce it. See a [working sample](https://github.com/OlgaMaciaszek/feign-eureka/tree/constructor-properties) (to reproduce, run a Eureka server `docker run -p 8761:8761 springcloud/demo-eureka-server:latest`, run `server` as a regular Boot app, build and run `client` with AOT, run HTTP call `http GET :7211/play`). If your issue persists, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue as a link to a GitHub repo with a small executable app.

**Comment by dpozinen** [comment]
Hi again @OlgaMaciaszek I finally got my hands on this again.
Your working sample works, because it does not build a native image, it lacks an `execution` to build it in the maven plugin. Indeed `process-aot` runs, but the resulting executable is not a AOT compiled native image.

Please have a look at [this fork](https://github.com/dpozinen/feign-eureka/tree/constructor-properties)

Use `mvn -Pnative -DskipTests package` in the `client` module and then run the binary `./target/feign-eureka-hello-client`. Use the same steps you specified to reproduce. The resulting log:
```
 Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: feign.codec.DecodeException: Error while extracting response for type [class demo.clients.HelloClient$PlayResponseValue] and content type [application/json]] with root cause

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `demo.clients.HelloClient$PlayResponseValue` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]

```

**Comment by OlgaMaciaszek** [comment]
Hello @dpozinen, by "run client with AOT" I meant creating an AOT-processed jar and running it. I've done it locally and haven't faced the issue you've described. I've pushed the AOT adjusted code [here](https://github.com/spring-cloud-samples/feign-eureka/tree/setup-AOT) now. Sorry if that was confusing. Will take a look at your fork.

**Comment by OlgaMaciaszek** [comment]
Thanks @dpozinen - was able to reproduce it with your sample. However, this does not seem to be an OpenFeign-specific issue. If you [comment-out any Spring Cloud-related code and just use `RestTemplate`](https://github.com/OlgaMaciaszek/feign-eureka/tree/constructor-properties-no-OF), you'll get the same exception. You may want to create an issue upstream ([Spring Framework](https://github.com/spring-projects/spring-framework)), but `@ConstructorProperties` may not be within the scope they support.
